////
// botany pots
//// renik

//
ServerEvents.recipes(event => {
//

  //REMOVE
// event.remove({ mod: 'botanypots' })
// event.remove({ mod: 'botanypotstiers' })
event.remove({ output: '#botanypots:all_botany_pots' })
// event.remove({id:/botanypots:mysticalagriculture\/crop/})


//
})

////
ServerEvents.recipes(event => {
//

  //ADD

// Botany Pot
  event.shaped('botanypots:terracotta_botany_pot',
    ['   ',' 2 ','212'], {
    1: 'supplementaries:planter',
    2: 'minecraft:terracotta'}).id('p2:terracotta_botany_pot')

// Botany Pot Colors
  event.shapeless(Item.of('botanypots:white_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:white_terracotta']).id('p2:white_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:white_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:white_concrete']).id('p2:white_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:white_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:white_glazed_terracotta']).id('p2:white_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:orange_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:orange_terracotta']).id('p2:orange_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:orange_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:orange_concrete']).id('p2:orange_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:orange_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:orange_glazed_terracotta']).id('p2:orange_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:magenta_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:magenta_terracotta']).id('p2:magenta_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:magenta_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:magenta_concrete']).id('p2:magenta_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:magenta_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:magenta_glazed_terracotta']).id('p2:magenta_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:light_blue_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:light_blue_terracotta']).id('p2:light_blue_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:light_blue_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:light_blue_concrete']).id('p2:light_blue_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:light_blue_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:light_blue_glazed_terracotta']).id('p2:light_blue_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:yellow_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:yellow_terracotta']).id('p2:yellow_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:yellow_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:yellow_concrete']).id('p2:yellow_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:yellow_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:yellow_glazed_terracotta']).id('p2:yellow_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:lime_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:lime_terracotta']).id('p2:lime_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:lime_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:lime_concrete']).id('p2:lime_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:lime_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:lime_glazed_terracotta']).id('p2:lime_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:pink_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:pink_terracotta']).id('p2:pink_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:pink_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:pink_concrete']).id('p2:pink_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:pink_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:pink_glazed_terracotta']).id('p2:pink_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:gray_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:gray_terracotta']).id('p2:gray_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:gray_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:gray_concrete']).id('p2:gray_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:gray_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:gray_glazed_terracotta']).id('p2:gray_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:light_gray_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:light_gray_terracotta']).id('p2:light_gray_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:light_gray_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:light_gray_concrete']).id('p2:light_gray_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:light_gray_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:light_gray_glazed_terracotta']).id('p2:light_gray_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:cyan_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:cyan_terracotta']).id('p2:cyan_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:cyan_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:cyan_concrete']).id('p2:cyan_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:cyan_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:cyan_glazed_terracotta']).id('p2:cyan_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:purple_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:purple_terracotta']).id('p2:purple_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:purple_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:purple_concrete']).id('p2:purple_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:purple_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:purple_glazed_terracotta']).id('p2:purple_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:blue_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:blue_terracotta']).id('p2:blue_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:blue_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:blue_concrete']).id('p2:blue_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:blue_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:blue_glazed_terracotta']).id('p2:blue_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:brown_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:brown_terracotta']).id('p2:brown_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:brown_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:brown_concrete']).id('p2:brown_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:brown_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:brown_glazed_terracotta']).id('p2:brown_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:green_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:green_terracotta']).id('p2:green_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:green_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:green_concrete']).id('p2:green_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:green_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:green_glazed_terracotta']).id('p2:green_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:red_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:red_terracotta']).id('p2:red_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:red_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:red_concrete']).id('p2:red_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:red_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:red_glazed_terracotta']).id('p2:red_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:black_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:black_terracotta']).id('p2:black_terracotta_botany_pot')
  event.shapeless(Item.of('botanypots:black_concrete_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:black_concrete']).id('p2:black_concrete_botany_pot')
  event.shapeless(Item.of('botanypots:black_glazed_terracotta_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:black_glazed_terracotta']).id('p2:black_glazed_terracotta_botany_pot')

// Hopper Botany Pot
  event.shapeless(Item.of('botanypots:terracotta_hopper_botany_pot'), ['botanypots:terracotta_botany_pot', 'minecraft:hopper']).id('p2:terracotta_hopper_botany_pot')

// Hopper Botany Pot Colors
  event.shapeless(Item.of('botanypots:white_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:white_terracotta']).id('p2:white_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:white_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:white_concrete']).id('p2:white_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:white_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:white_glazed_terracotta']).id('p2:white_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:orange_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:orange_terracotta']).id('p2:orange_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:orange_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:orange_concrete']).id('p2:orange_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:orange_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:orange_glazed_terracotta']).id('p2:orange_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:magenta_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:magenta_terracotta']).id('p2:magenta_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:magenta_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:magenta_concrete']).id('p2:magenta_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:magenta_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:magenta_glazed_terracotta']).id('p2:magenta_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:light_blue_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:light_blue_terracotta']).id('p2:light_blue_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:light_blue_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:light_blue_concrete']).id('p2:light_blue_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:light_blue_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:light_blue_glazed_terracotta']).id('p2:light_blue_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:yellow_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:yellow_terracotta']).id('p2:yellow_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:yellow_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:yellow_concrete']).id('p2:yellow_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:yellow_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:yellow_glazed_terracotta']).id('p2:yellow_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:lime_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:lime_terracotta']).id('p2:lime_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:lime_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:lime_concrete']).id('p2:lime_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:lime_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:lime_glazed_terracotta']).id('p2:lime_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:pink_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:pink_terracotta']).id('p2:pink_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:pink_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:pink_concrete']).id('p2:pink_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:pink_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:pink_glazed_terracotta']).id('p2:pink_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:gray_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:gray_terracotta']).id('p2:gray_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:gray_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:gray_concrete']).id('p2:gray_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:gray_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:gray_glazed_terracotta']).id('p2:gray_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:light_gray_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:light_gray_terracotta']).id('p2:light_gray_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:light_gray_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:light_gray_concrete']).id('p2:light_gray_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:light_gray_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:light_gray_glazed_terracotta']).id('p2:light_gray_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:cyan_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:cyan_terracotta']).id('p2:cyan_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:cyan_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:cyan_concrete']).id('p2:cyan_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:cyan_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:cyan_glazed_terracotta']).id('p2:cyan_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:purple_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:purple_terracotta']).id('p2:purple_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:purple_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:purple_concrete']).id('p2:purple_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:purple_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:purple_glazed_terracotta']).id('p2:purple_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:blue_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:blue_terracotta']).id('p2:blue_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:blue_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:blue_concrete']).id('p2:blue_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:blue_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:blue_glazed_terracotta']).id('p2:blue_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:brown_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:brown_terracotta']).id('p2:brown_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:brown_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:brown_concrete']).id('p2:brown_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:brown_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:brown_glazed_terracotta']).id('p2:brown_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:green_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:green_terracotta']).id('p2:green_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:green_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:green_concrete']).id('p2:green_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:green_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:green_glazed_terracotta']).id('p2:green_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:red_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:red_terracotta']).id('p2:red_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:red_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:red_concrete']).id('p2:red_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:red_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:red_glazed_terracotta']).id('p2:red_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:black_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:black_terracotta']).id('p2:black_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:black_concrete_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:black_concrete']).id('p2:black_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypots:black_glazed_terracotta_hopper_botany_pot'), ['botanypots:terracotta_hopper_botany_pot', 'minecraft:black_glazed_terracotta']).id('p2:black_glazed_terracotta_hopper_botany_pot')

// Elite Botany Pot
  event.shaped('botanypotstiers:elite_terracotta_botany_pot',
    ['   ',' 2 ','313'], {
    1: 'botanypots:terracotta_botany_pot',
    2: 'mysticalagriculture:tertium_gemstone',
    3: 'mysticalagriculture:prudentium_essence'}).id('p2:elite_terracotta_botany_pot')

// Elite Botany Pot Colors
  event.shapeless(Item.of('botanypotstiers:elite_white_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:white_terracotta']).id('p2:elite_white_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_white_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:white_concrete']).id('p2:elite_white_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_white_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:white_glazed_terracotta']).id('p2:elite_white_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_orange_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:orange_terracotta']).id('p2:elite_orange_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_orange_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:orange_concrete']).id('p2:elite_orange_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_orange_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:orange_glazed_terracotta']).id('p2:elite_orange_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_magenta_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:magenta_terracotta']).id('p2:elite_magenta_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_magenta_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:magenta_concrete']).id('p2:elite_magenta_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_magenta_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:magenta_glazed_terracotta']).id('p2:elite_magenta_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_blue_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:light_blue_terracotta']).id('p2:elite_light_blue_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_blue_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:light_blue_concrete']).id('p2:elite_light_blue_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_blue_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:light_blue_glazed_terracotta']).id('p2:elite_light_blue_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_yellow_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:yellow_terracotta']).id('p2:elite_yellow_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_yellow_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:yellow_concrete']).id('p2:elite_yellow_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_yellow_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:yellow_glazed_terracotta']).id('p2:elite_yellow_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_lime_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:lime_terracotta']).id('p2:elite_lime_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_lime_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:lime_concrete']).id('p2:elite_lime_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_lime_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:lime_glazed_terracotta']).id('p2:elite_lime_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_pink_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:pink_terracotta']).id('p2:elite_pink_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_pink_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:pink_concrete']).id('p2:elite_pink_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_pink_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:pink_glazed_terracotta']).id('p2:elite_pink_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_gray_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:gray_terracotta']).id('p2:elite_gray_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_gray_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:gray_concrete']).id('p2:elite_gray_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_gray_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:gray_glazed_terracotta']).id('p2:elite_gray_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_gray_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:light_gray_terracotta']).id('p2:elite_light_gray_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_gray_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:light_gray_concrete']).id('p2:elite_light_gray_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_gray_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:light_gray_glazed_terracotta']).id('p2:elite_light_gray_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_cyan_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:cyan_terracotta']).id('p2:elite_cyan_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_cyan_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:cyan_concrete']).id('p2:elite_cyan_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_cyan_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:cyan_glazed_terracotta']).id('p2:elite_cyan_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_purple_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:purple_terracotta']).id('p2:elite_purple_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_purple_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:purple_concrete']).id('p2:elite_purple_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_purple_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:purple_glazed_terracotta']).id('p2:elite_purple_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_blue_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:blue_terracotta']).id('p2:elite_blue_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_blue_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:blue_concrete']).id('p2:elite_blue_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_blue_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:blue_glazed_terracotta']).id('p2:elite_blue_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_brown_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:brown_terracotta']).id('p2:elite_brown_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_brown_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:brown_concrete']).id('p2:elite_brown_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_brown_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:brown_glazed_terracotta']).id('p2:elite_brown_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_green_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:green_terracotta']).id('p2:elite_green_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_green_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:green_concrete']).id('p2:elite_green_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_green_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:green_glazed_terracotta']).id('p2:elite_green_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_red_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:red_terracotta']).id('p2:elite_red_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_red_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:red_concrete']).id('p2:elite_red_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_red_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:red_glazed_terracotta']).id('p2:elite_red_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_black_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:black_terracotta']).id('p2:elite_black_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_black_concrete_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:black_concrete']).id('p2:elite_black_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_black_glazed_terracotta_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:black_glazed_terracotta']).id('p2:elite_black_glazed_terracotta_botany_pot')

// Elite Hopper Botany Pot
  event.shapeless(Item.of('botanypotstiers:elite_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_botany_pot', 'minecraft:hopper']).id('p2:elite_terracotta_hopper_botany_pot')
 
 // elite Hopper Botany Pot Colors
  event.shapeless(Item.of('botanypotstiers:elite_white_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:white_terracotta']).id('p2:elite_white_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_white_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:white_concrete']).id('p2:elite_white_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_white_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:white_glazed_terracotta']).id('p2:elite_white_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_orange_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:orange_terracotta']).id('p2:elite_orange_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_orange_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:orange_concrete']).id('p2:elite_orange_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_orange_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:orange_glazed_terracotta']).id('p2:elite_orange_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_magenta_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:magenta_terracotta']).id('p2:elite_magenta_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_magenta_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:magenta_concrete']).id('p2:elite_magenta_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_magenta_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:magenta_glazed_terracotta']).id('p2:elite_magenta_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_blue_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:light_blue_terracotta']).id('p2:elite_light_blue_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_blue_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:light_blue_concrete']).id('p2:elite_light_blue_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_blue_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:light_blue_glazed_terracotta']).id('p2:elite_light_blue_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_yellow_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:yellow_terracotta']).id('p2:elite_yellow_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_yellow_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:yellow_concrete']).id('p2:elite_yellow_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_yellow_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:yellow_glazed_terracotta']).id('p2:elite_yellow_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_lime_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:lime_terracotta']).id('p2:elite_lime_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_lime_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:lime_concrete']).id('p2:elite_lime_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_lime_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:lime_glazed_terracotta']).id('p2:elite_lime_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_pink_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:pink_terracotta']).id('p2:elite_pink_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_pink_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:pink_concrete']).id('p2:elite_pink_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_pink_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:pink_glazed_terracotta']).id('p2:elite_pink_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_gray_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:gray_terracotta']).id('p2:elite_gray_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_gray_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:gray_concrete']).id('p2:elite_gray_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_gray_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:gray_glazed_terracotta']).id('p2:elite_gray_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_gray_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:light_gray_terracotta']).id('p2:elite_light_gray_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_gray_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:light_gray_concrete']).id('p2:elite_light_gray_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_light_gray_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:light_gray_glazed_terracotta']).id('p2:elite_light_gray_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_cyan_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:cyan_terracotta']).id('p2:elite_cyan_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_cyan_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:cyan_concrete']).id('p2:elite_cyan_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_cyan_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:cyan_glazed_terracotta']).id('p2:elite_cyan_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_purple_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:purple_terracotta']).id('p2:elite_purple_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_purple_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:purple_concrete']).id('p2:elite_purple_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_purple_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:purple_glazed_terracotta']).id('p2:elite_purple_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_blue_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:blue_terracotta']).id('p2:elite_blue_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_blue_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:blue_concrete']).id('p2:elite_blue_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_blue_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:blue_glazed_terracotta']).id('p2:elite_blue_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_brown_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:brown_terracotta']).id('p2:elite_brown_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_brown_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:brown_concrete']).id('p2:elite_brown_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_brown_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:brown_glazed_terracotta']).id('p2:elite_brown_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_green_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:green_terracotta']).id('p2:elite_green_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_green_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:green_concrete']).id('p2:elite_green_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_green_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:green_glazed_terracotta']).id('p2:elite_green_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_red_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:red_terracotta']).id('p2:elite_red_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_red_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:red_concrete']).id('p2:elite_red_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_red_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:red_glazed_terracotta']).id('p2:elite_red_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_black_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:black_terracotta']).id('p2:elite_black_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_black_concrete_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:black_concrete']).id('p2:elite_black_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:elite_black_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:elite_terracotta_hopper_botany_pot', 'minecraft:black_glazed_terracotta']).id('p2:elite_black_glazed_terracotta_hopper_botany_pot')

// Ultra Botany Pot
  event.shaped('botanypotstiers:ultra_terracotta_botany_pot',
    ['   ',' 2 ','313'], {
    1: 'botanypotstiers:elite_terracotta_botany_pot',
    2: 'mysticalagriculture:supremium_gemstone',
    3: 'mysticalagriculture:imperium_essence'}).id('p2:ultra_terracotta_botany_pot')

// Ultra Botany Pot Colors
  event.shapeless(Item.of('botanypotstiers:ultra_white_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:white_terracotta']).id('p2:ultra_white_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_white_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:white_concrete']).id('p2:ultra_white_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_white_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:white_glazed_terracotta']).id('p2:ultra_white_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_orange_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:orange_terracotta']).id('p2:ultra_orange_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_orange_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:orange_concrete']).id('p2:ultra_orange_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_orange_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:orange_glazed_terracotta']).id('p2:ultra_orange_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_magenta_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:magenta_terracotta']).id('p2:ultra_magenta_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_magenta_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:magenta_concrete']).id('p2:ultra_magenta_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_magenta_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:magenta_glazed_terracotta']).id('p2:ultra_magenta_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_blue_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:light_blue_terracotta']).id('p2:ultra_light_blue_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_blue_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:light_blue_concrete']).id('p2:ultra_light_blue_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_blue_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:light_blue_glazed_terracotta']).id('p2:ultra_light_blue_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_yellow_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:yellow_terracotta']).id('p2:ultra_yellow_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_yellow_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:yellow_concrete']).id('p2:ultra_yellow_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_yellow_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:yellow_glazed_terracotta']).id('p2:ultra_yellow_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_lime_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:lime_terracotta']).id('p2:ultra_lime_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_lime_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:lime_concrete']).id('p2:ultra_lime_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_lime_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:lime_glazed_terracotta']).id('p2:ultra_lime_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_pink_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:pink_terracotta']).id('p2:ultra_pink_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_pink_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:pink_concrete']).id('p2:ultra_pink_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_pink_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:pink_glazed_terracotta']).id('p2:ultra_pink_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_gray_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:gray_terracotta']).id('p2:ultra_gray_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_gray_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:gray_concrete']).id('p2:ultra_gray_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_gray_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:gray_glazed_terracotta']).id('p2:ultra_gray_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_gray_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:light_gray_terracotta']).id('p2:ultra_light_gray_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_gray_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:light_gray_concrete']).id('p2:ultra_light_gray_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_gray_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:light_gray_glazed_terracotta']).id('p2:ultra_light_gray_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_cyan_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:cyan_terracotta']).id('p2:ultra_cyan_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_cyan_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:cyan_concrete']).id('p2:ultra_cyan_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_cyan_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:cyan_glazed_terracotta']).id('p2:ultra_cyan_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_purple_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:purple_terracotta']).id('p2:ultra_purple_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_purple_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:purple_concrete']).id('p2:ultra_purple_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_purple_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:purple_glazed_terracotta']).id('p2:ultra_purple_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_blue_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:blue_terracotta']).id('p2:ultra_blue_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_blue_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:blue_concrete']).id('p2:ultra_blue_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_blue_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:blue_glazed_terracotta']).id('p2:ultra_blue_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_brown_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:brown_terracotta']).id('p2:ultra_brown_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_brown_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:brown_concrete']).id('p2:ultra_brown_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_brown_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:brown_glazed_terracotta']).id('p2:ultra_brown_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_green_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:green_terracotta']).id('p2:ultra_green_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_green_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:green_concrete']).id('p2:ultra_green_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_green_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:green_glazed_terracotta']).id('p2:ultra_green_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_red_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:red_terracotta']).id('p2:ultra_red_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_red_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:red_concrete']).id('p2:ultra_red_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_red_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:red_glazed_terracotta']).id('p2:ultra_red_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_black_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:black_terracotta']).id('p2:ultra_black_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_black_concrete_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:black_concrete']).id('p2:ultra_black_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_black_glazed_terracotta_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:black_glazed_terracotta']).id('p2:ultra_black_glazed_terracotta_botany_pot')

// Ultra Hopper Botany Pot
  event.shapeless(Item.of('botanypotstiers:ultra_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_botany_pot', 'minecraft:hopper']).id('p2:ultra_terracotta_hopper_botany_pot')

 // ultra Hopper Botany Pot Colors
  event.shapeless(Item.of('botanypotstiers:ultra_white_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:white_terracotta']).id('p2:ultra_white_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_white_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:white_concrete']).id('p2:ultra_white_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_white_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:white_glazed_terracotta']).id('p2:ultra_white_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_orange_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:orange_terracotta']).id('p2:ultra_orange_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_orange_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:orange_concrete']).id('p2:ultra_orange_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_orange_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:orange_glazed_terracotta']).id('p2:ultra_orange_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_magenta_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:magenta_terracotta']).id('p2:ultra_magenta_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_magenta_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:magenta_concrete']).id('p2:ultra_magenta_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_magenta_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:magenta_glazed_terracotta']).id('p2:ultra_magenta_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_blue_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:light_blue_terracotta']).id('p2:ultra_light_blue_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_blue_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:light_blue_concrete']).id('p2:ultra_light_blue_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_blue_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:light_blue_glazed_terracotta']).id('p2:ultra_light_blue_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_yellow_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:yellow_terracotta']).id('p2:ultra_yellow_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_yellow_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:yellow_concrete']).id('p2:ultra_yellow_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_yellow_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:yellow_glazed_terracotta']).id('p2:ultra_yellow_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_lime_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:lime_terracotta']).id('p2:ultra_lime_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_lime_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:lime_concrete']).id('p2:ultra_lime_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_lime_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:lime_glazed_terracotta']).id('p2:ultra_lime_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_pink_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:pink_terracotta']).id('p2:ultra_pink_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_pink_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:pink_concrete']).id('p2:ultra_pink_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_pink_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:pink_glazed_terracotta']).id('p2:ultra_pink_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_gray_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:gray_terracotta']).id('p2:ultra_gray_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_gray_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:gray_concrete']).id('p2:ultra_gray_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_gray_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:gray_glazed_terracotta']).id('p2:ultra_gray_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_gray_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:light_gray_terracotta']).id('p2:ultra_light_gray_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_gray_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:light_gray_concrete']).id('p2:ultra_light_gray_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_light_gray_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:light_gray_glazed_terracotta']).id('p2:ultra_light_gray_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_cyan_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:cyan_terracotta']).id('p2:ultra_cyan_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_cyan_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:cyan_concrete']).id('p2:ultra_cyan_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_cyan_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:cyan_glazed_terracotta']).id('p2:ultra_cyan_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_purple_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:purple_terracotta']).id('p2:ultra_purple_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_purple_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:purple_concrete']).id('p2:ultra_purple_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_purple_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:purple_glazed_terracotta']).id('p2:ultra_purple_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_blue_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:blue_terracotta']).id('p2:ultra_blue_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_blue_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:blue_concrete']).id('p2:ultra_blue_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_blue_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:blue_glazed_terracotta']).id('p2:ultra_blue_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_brown_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:brown_terracotta']).id('p2:ultra_brown_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_brown_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:brown_concrete']).id('p2:ultra_brown_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_brown_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:brown_glazed_terracotta']).id('p2:ultra_brown_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_green_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:green_terracotta']).id('p2:ultra_green_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_green_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:green_concrete']).id('p2:ultra_green_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_green_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:green_glazed_terracotta']).id('p2:ultra_green_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_red_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:red_terracotta']).id('p2:ultra_red_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_red_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:red_concrete']).id('p2:ultra_red_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_red_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:red_glazed_terracotta']).id('p2:ultra_red_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_black_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:black_terracotta']).id('p2:ultra_black_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_black_concrete_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:black_concrete']).id('p2:ultra_black_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:ultra_black_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:ultra_terracotta_hopper_botany_pot', 'minecraft:black_glazed_terracotta']).id('p2:ultra_black_glazed_terracotta_hopper_botany_pot')

// Creative Botany Pot
  event.shaped('botanypotstiers:creative_terracotta_botany_pot',
    ['   ',' 2 ','313'], {
    1: 'botanypotstiers:ultra_terracotta_botany_pot',
    2: 'mysticalagradditions:insanium_gemstone',
    3: 'mysticalagradditions:creative_essence'}).id('p2:creative_terracotta_botany_pot')

// Creative Botany Pot Colors
  event.shapeless(Item.of('botanypotstiers:creative_white_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:white_terracotta']).id('p2:creative_white_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_white_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:white_concrete']).id('p2:creative_white_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_white_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:white_glazed_terracotta']).id('p2:creative_white_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_orange_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:orange_terracotta']).id('p2:creative_orange_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_orange_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:orange_concrete']).id('p2:creative_orange_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_orange_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:orange_glazed_terracotta']).id('p2:creative_orange_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_magenta_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:magenta_terracotta']).id('p2:creative_magenta_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_magenta_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:magenta_concrete']).id('p2:creative_magenta_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_magenta_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:magenta_glazed_terracotta']).id('p2:creative_magenta_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_blue_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:light_blue_terracotta']).id('p2:creative_light_blue_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_blue_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:light_blue_concrete']).id('p2:creative_light_blue_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_blue_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:light_blue_glazed_terracotta']).id('p2:creative_light_blue_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_yellow_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:yellow_terracotta']).id('p2:creative_yellow_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_yellow_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:yellow_concrete']).id('p2:creative_yellow_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_yellow_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:yellow_glazed_terracotta']).id('p2:creative_yellow_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_lime_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:lime_terracotta']).id('p2:creative_lime_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_lime_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:lime_concrete']).id('p2:creative_lime_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_lime_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:lime_glazed_terracotta']).id('p2:creative_lime_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_pink_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:pink_terracotta']).id('p2:creative_pink_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_pink_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:pink_concrete']).id('p2:creative_pink_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_pink_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:pink_glazed_terracotta']).id('p2:creative_pink_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_gray_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:gray_terracotta']).id('p2:creative_gray_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_gray_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:gray_concrete']).id('p2:creative_gray_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_gray_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:gray_glazed_terracotta']).id('p2:creative_gray_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_gray_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:light_gray_terracotta']).id('p2:creative_light_gray_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_gray_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:light_gray_concrete']).id('p2:creative_light_gray_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_gray_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:light_gray_glazed_terracotta']).id('p2:creative_light_gray_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_cyan_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:cyan_terracotta']).id('p2:creative_cyan_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_cyan_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:cyan_concrete']).id('p2:creative_cyan_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_cyan_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:cyan_glazed_terracotta']).id('p2:creative_cyan_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_purple_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:purple_terracotta']).id('p2:creative_purple_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_purple_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:purple_concrete']).id('p2:creative_purple_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_purple_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:purple_glazed_terracotta']).id('p2:creative_purple_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_blue_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:blue_terracotta']).id('p2:creative_blue_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_blue_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:blue_concrete']).id('p2:creative_blue_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_blue_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:blue_glazed_terracotta']).id('p2:creative_blue_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_brown_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:brown_terracotta']).id('p2:creative_brown_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_brown_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:brown_concrete']).id('p2:creative_brown_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_brown_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:brown_glazed_terracotta']).id('p2:creative_brown_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_green_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:green_terracotta']).id('p2:creative_green_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_green_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:green_concrete']).id('p2:creative_green_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_green_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:green_glazed_terracotta']).id('p2:creative_green_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_red_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:red_terracotta']).id('p2:creative_red_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_red_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:red_concrete']).id('p2:creative_red_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_red_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:red_glazed_terracotta']).id('p2:creative_red_glazed_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_black_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:black_terracotta']).id('p2:creative_black_terracotta_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_black_concrete_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:black_concrete']).id('p2:creative_black_concrete_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_black_glazed_terracotta_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:black_glazed_terracotta']).id('p2:creative_black_glazed_terracotta_botany_pot')

// Creative Hopper Botany Pot
  event.shapeless(Item.of('botanypotstiers:creative_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_botany_pot', 'minecraft:hopper']).id('p2:creative_terracotta_hopper_botany_pot')

// creative Hopper Botany Pot Colors
  event.shapeless(Item.of('botanypotstiers:creative_white_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:white_terracotta']).id('p2:creative_white_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_white_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:white_concrete']).id('p2:creative_white_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_white_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:white_glazed_terracotta']).id('p2:creative_white_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_orange_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:orange_terracotta']).id('p2:creative_orange_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_orange_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:orange_concrete']).id('p2:creative_orange_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_orange_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:orange_glazed_terracotta']).id('p2:creative_orange_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_magenta_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:magenta_terracotta']).id('p2:creative_magenta_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_magenta_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:magenta_concrete']).id('p2:creative_magenta_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_magenta_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:magenta_glazed_terracotta']).id('p2:creative_magenta_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_blue_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:light_blue_terracotta']).id('p2:creative_light_blue_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_blue_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:light_blue_concrete']).id('p2:creative_light_blue_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_blue_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:light_blue_glazed_terracotta']).id('p2:creative_light_blue_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_yellow_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:yellow_terracotta']).id('p2:creative_yellow_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_yellow_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:yellow_concrete']).id('p2:creative_yellow_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_yellow_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:yellow_glazed_terracotta']).id('p2:creative_yellow_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_lime_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:lime_terracotta']).id('p2:creative_lime_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_lime_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:lime_concrete']).id('p2:creative_lime_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_lime_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:lime_glazed_terracotta']).id('p2:creative_lime_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_pink_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:pink_terracotta']).id('p2:creative_pink_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_pink_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:pink_concrete']).id('p2:creative_pink_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_pink_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:pink_glazed_terracotta']).id('p2:creative_pink_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_gray_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:gray_terracotta']).id('p2:creative_gray_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_gray_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:gray_concrete']).id('p2:creative_gray_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_gray_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:gray_glazed_terracotta']).id('p2:creative_gray_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_gray_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:light_gray_terracotta']).id('p2:creative_light_gray_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_gray_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:light_gray_concrete']).id('p2:creative_light_gray_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_light_gray_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:light_gray_glazed_terracotta']).id('p2:creative_light_gray_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_cyan_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:cyan_terracotta']).id('p2:creative_cyan_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_cyan_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:cyan_concrete']).id('p2:creative_cyan_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_cyan_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:cyan_glazed_terracotta']).id('p2:creative_cyan_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_purple_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:purple_terracotta']).id('p2:creative_purple_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_purple_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:purple_concrete']).id('p2:creative_purple_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_purple_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:purple_glazed_terracotta']).id('p2:creative_purple_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_blue_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:blue_terracotta']).id('p2:creative_blue_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_blue_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:blue_concrete']).id('p2:creative_blue_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_blue_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:blue_glazed_terracotta']).id('p2:creative_blue_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_brown_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:brown_terracotta']).id('p2:creative_brown_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_brown_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:brown_concrete']).id('p2:creative_brown_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_brown_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:brown_glazed_terracotta']).id('p2:creative_brown_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_green_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:green_terracotta']).id('p2:creative_green_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_green_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:green_concrete']).id('p2:creative_green_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_green_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:green_glazed_terracotta']).id('p2:creative_green_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_red_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:red_terracotta']).id('p2:creative_red_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_red_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:red_concrete']).id('p2:creative_red_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_red_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:red_glazed_terracotta']).id('p2:creative_red_glazed_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_black_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:black_terracotta']).id('p2:creative_black_terracotta_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_black_concrete_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:black_concrete']).id('p2:creative_black_concrete_hopper_botany_pot')
  event.shapeless(Item.of('botanypotstiers:creative_black_glazed_terracotta_hopper_botany_pot'), ['botanypotstiers:creative_terracotta_hopper_botany_pot', 'minecraft:black_glazed_terracotta']).id('p2:creative_black_glazed_terracotta_hopper_botany_pot')

//    
})
//